name: Add to OSS board

on:
  issues:
    types:
      - opened
      - reopened
      - transferred
      - labeled

jobs:

  run:
    uses: "anchore/workflows/.github/workflows/oss-project-board-add.yaml@main"
    secrets:
      token: ${{ secrets.ORG_REPO_TOKEN }}
